-- generated by tests/milestone_lockdown.lua — do not edit by hand
-- locked: 2026-09-09 02:28:30
-- rustc 1.98.1 (48a229cea 2026-09-01) (Arch Linux rust 1:1.98.1-1.1)
-- TIME 2.713µs — bug_01.lua
-- TIME 5.546µs — bug_02.lua
-- TIME 4.774µs — bug_03.lua
-- TIME 11.462µs — bug_04.lua
-- TIME 1.863µs — bug_06.lua
-- TIME 5.429µs — bug_07a.lua
-- TIME 4.172µs — bug_07b.lua
-- TIME 2.196µs — bug_08.lua
-- TIME 165.99µs — bug_09.lua
-- TIME 3.253µs — bug_10b.lua
-- TIME 1.079µs — bug_11.lua
-- TIME 2.528µs — bug_12.lua
-- TIME 2.076µs — bug_13.lua
-- TIME 238.487µs — optfast.lua
-- TIME 959ns — bug_16a.lua
-- TIME 1.961µs — bug_16b.lua
-- TIME 998ns — bug_17.lua
-- TIME 900ns — bug_18.lua
-- TIME 2.334µs — gauntlet_pA.lua
-- TIME 10.581µs — gauntlet_pB.lua
-- TIME 3.391µs — gauntlet_pC.lua
-- TIME 1.763µs — gauntlet_pD.lua
-- TIME 292ns — gauntlet_pE.lua
-- TIME 6.412µs — gauntlet_pF.lua
-- TIME 1.9µs — gauntlet_pG.lua
-- TIME 4.027µs — gauntlet_pH.lua
-- TIME 1.17µs — gauntlet_pI.lua
-- TIME 5.229µs — gauntlet_pJ.lua
-- TIME 33.449µs — gauntlet_pK.lua
-- TIME 263ns — gauntlet_pL.lua
-- TIME 1.043µs — gauntlet_pM.lua
-- TIME 953ns — opt_literal_bound.lua
-- TIME 4.523µs — region_table_resize.lua
-- TIME 5.228µs — hoist_ctx_showcase.lua
-- TIME 246ns — tier2_reg_limit.lua
-- TIME 1.169µs — firewall_abort_all.lua
-- TIME 1.082µs — firewall_global_offset.lua
-- TIME 962ns — firewall_neg_offset.lua
-- TIME 2.016190132s — gauntlet_main.lua
-- TIME 993ns — nested_01_success.lua
-- TIME 734ns — nested_05_dyn_loop.lua
-- TIME 196ns — nested_06_read_before_write.lua
-- TIME 3.726µs — nested_07_read_then_table_store.lua
-- TIME 2.637µs — nested_08_fresh_store.lua
-- TIME 3.497µs — nested_10_alias_shared.lua
-- TIME 4.008µs — nested_15_read_then_fresh.lua
-- TIME 1.309µs — float_01_store_read.lua
-- TIME 1.176µs — float_02_loop_gate.lua
-- TIME 914ns — float_06_lazy_read.lua
-- TIME 207ns — float_09_fast_rw.lua
-- TIME 1.059µs — float_10_handle_mode.lua
-- TIME 1.975µs — tier4_01_flat_plus_nested.lua
-- TIME 1.778µs — tier4_02_nested_read.lua
-- TIME 1.137µs — tier4_03_rebind_decline.lua
-- TIME 3.107µs — tier4_04_zero_iter.lua
-- TIME 2.46µs — tier4_06_float_child.lua
-- TIME 1.237µs — tier4_07_reg_limit_decline.lua
-- TIME 283ns — tier4_08_zero_trip_init.lua
-- TIME 1.263µs — tier4_09_multihop.lua
-- TIME 1.85µs — tier4_10_matrix.lua
-- TIME 3.355µs — tier4_11_matrix_float.lua
-- TIME 1.368µs — tier4_12_unprovable_limit.lua
return {
    "bug_01.lua",
    "bug_02.lua",
    "bug_03.lua",
    "bug_04.lua",
    "bug_06.lua",
    "bug_07a.lua",
    "bug_07b.lua",
    "bug_08.lua",
    "bug_09.lua",
    "bug_10b.lua",
    "bug_11.lua",
    "bug_12.lua",
    "bug_13.lua",
    "optfast.lua",
    "bug_16a.lua",
    "bug_16b.lua",
    "bug_17.lua",
    "bug_18.lua",
    "gauntlet_pA.lua",
    "gauntlet_pB.lua",
    "gauntlet_pC.lua",
    "gauntlet_pD.lua",
    "gauntlet_pE.lua",
    "gauntlet_pF.lua",
    "gauntlet_pG.lua",
    "gauntlet_pH.lua",
    "gauntlet_pI.lua",
    "gauntlet_pJ.lua",
    "gauntlet_pK.lua",
    "gauntlet_pL.lua",
    "gauntlet_pM.lua",
    "opt_literal_bound.lua",
    "region_table_resize.lua",
    "hoist_ctx_showcase.lua",
    "tier2_reg_limit.lua",
    "firewall_abort_all.lua",
    "firewall_global_offset.lua",
    "firewall_neg_offset.lua",
    "gauntlet_main.lua",
    "nested_01_success.lua",
    "nested_05_dyn_loop.lua",
    "nested_06_read_before_write.lua",
    "nested_07_read_then_table_store.lua",
    "nested_08_fresh_store.lua",
    "nested_10_alias_shared.lua",
    "nested_15_read_then_fresh.lua",
    "float_01_store_read.lua",
    "float_02_loop_gate.lua",
    "float_06_lazy_read.lua",
    "float_09_fast_rw.lua",
    "float_10_handle_mode.lua",
    "tier4_01_flat_plus_nested.lua",
    "tier4_02_nested_read.lua",
    "tier4_03_rebind_decline.lua",
    "tier4_04_zero_iter.lua",
    "tier4_06_float_child.lua",
    "tier4_07_reg_limit_decline.lua",
    "tier4_08_zero_trip_init.lua",
    "tier4_09_multihop.lua",
    "tier4_10_matrix.lua",
    "tier4_11_matrix_float.lua",
    "tier4_12_unprovable_limit.lua",
}
