-- generated by tests/milestone_lockdown.lua — do not edit by hand
-- locked: 2026-09-10 12:40:24
-- rustc 1.98.1 (48a229cea 2026-09-01) (Arch Linux rust 1:1.98.1-1.1)
-- TIME 3.179µs — bug_01.lua
-- TIME 2.113µs — bug_02.lua
-- TIME 2.633µs — bug_03.lua
-- TIME 9.811µs — bug_04.lua
-- TIME 2.188µs — bug_06.lua
-- TIME 4.753µs — bug_07a.lua
-- TIME 4.329µs — bug_07b.lua
-- TIME 2.269µs — bug_08.lua
-- TIME 124.239µs — bug_09.lua
-- TIME 2.864µs — bug_10b.lua
-- TIME 997ns — bug_11.lua
-- TIME 2.909µs — bug_12.lua
-- TIME 2.357µs — bug_13.lua
-- TIME 206.448µs — optfast.lua
-- TIME 965ns — bug_16a.lua
-- TIME 3.138µs — bug_16b.lua
-- TIME 887ns — bug_17.lua
-- TIME 902ns — bug_18.lua
-- TIME 2.173µs — gauntlet_pA.lua
-- TIME 11.471µs — gauntlet_pB.lua
-- TIME 1.14µs — gauntlet_pC.lua
-- TIME 1.998µs — gauntlet_pD.lua
-- TIME 266ns — gauntlet_pE.lua
-- TIME 4.126µs — gauntlet_pF.lua
-- TIME 1.902µs — gauntlet_pG.lua
-- TIME 2.725µs — gauntlet_pH.lua
-- TIME 1.012µs — gauntlet_pI.lua
-- TIME 2.719µs — gauntlet_pJ.lua
-- TIME 33.433µs — gauntlet_pK.lua
-- TIME 257ns — gauntlet_pL.lua
-- TIME 1.374µs — gauntlet_pM.lua
-- TIME 1.194µs — opt_literal_bound.lua
-- TIME 2.092µs — region_table_resize.lua
-- TIME 5.258µs — hoist_ctx_showcase.lua
-- TIME 235ns — tier2_reg_limit.lua
-- TIME 1.098µs — firewall_abort_all.lua
-- TIME 1.085µs — firewall_global_offset.lua
-- TIME 1.022µs — firewall_neg_offset.lua
-- TIME 1.92725167s — gauntlet_main.lua
-- TIME 334.294µs — gauntlet_float.lua
-- TIME 1.057µs — nested_01_success.lua
-- TIME 647ns — nested_05_dyn_loop.lua
-- TIME 157ns — nested_06_read_before_write.lua
-- TIME 1.905µs — nested_07_read_then_table_store.lua
-- TIME 2.314µs — nested_08_fresh_store.lua
-- TIME 1.344µs — nested_10_alias_shared.lua
-- TIME 1.889µs — nested_15_read_then_fresh.lua
-- TIME 1.515µs — float_01_store_read.lua
-- TIME 1.012µs — float_02_loop_gate.lua
-- TIME 914ns — float_06_lazy_read.lua
-- TIME 210ns — float_09_fast_rw.lua
-- TIME 1.084µs — float_10_handle_mode.lua
-- TIME 340ns — float_14_add_store.lua
-- TIME 629.7177ms — float_15_barista_space_cafe.lua
-- TIME 2.166µs — tier4_01_flat_plus_nested.lua
-- TIME 2.326µs — tier4_02_nested_read.lua
-- TIME 1.034µs — tier4_03_rebind_decline.lua
-- TIME 912ns — tier4_04_zero_iter.lua
-- TIME 1.698µs — tier4_06_float_child.lua
-- TIME 1.105µs — tier4_07_reg_limit_decline.lua
-- TIME 332ns — tier4_08_zero_trip_init.lua
-- TIME 1.338µs — tier4_09_multihop.lua
-- TIME 1.377µs — tier4_10_matrix.lua
-- TIME 1.427µs — tier4_11_matrix_float.lua
-- TIME 1.328µs — tier4_12_unprovable_limit.lua
-- TIME 2.298µs — tier4_13_matrix_fast_row.lua
-- TIME 1.336µs — tier4_14_matrix_alias_decline.lua
-- TIME 1.68µs — tier4_15_matrix_copy_reach.lua
-- TIME 988ns — feat_if_01_phi_merge.lua
-- TIME 1.863µs — feat_ops_01_arith.lua
-- TIME 922ns — feat_ops_02_compare_bool.lua
-- TIME 999ns — feat_ops_03_fast_leq.lua
-- TIME 2.108µs — feat_ops_04_floor_neg.lua
-- TIME 188ns — feat_ops_05_cmp_corners.lua
-- TIME 175ns — feat_ops_06_bool_eq_variants.lua
-- TIME 2.169µs — feat_ops_07_neg_zero.lua
-- TIME 302ns — feat_ops_08_loop_forms.lua
-- TIME 1.003µs — feat_ops_09_paren_gate.lua
-- TIME 1.168µs — feat_ops_10_float_specials.lua
-- TIME 211ns — feat_ops_11_precedence.lua
-- TIME 201ns — feat_ops_12_if_store_gate.lua
-- TIME 253ns — feat_if_02_phi_variants.lua
-- TIME 1.03µs — feat_if_03_scope_shadow.lua
-- TIME 4.533µs — probe_01_scalar.lua
-- TIME 7.53µs — probe_02_loop_phi.lua
-- TIME 3.828µs — probe_03_ec_offset.lua
-- TIME 7.026µs — probe_04_leq_desugar_ec.lua
-- TIME 5.946µs — probe_05_hoist_stability.lua
-- TIME 7.352µs — probe_06_ssa_names.lua
-- TIME 6.387µs — probe_07_mint_child.lua
-- TIME 6.516µs — string_01_scalar.lua
-- TIME 7.599µs — string_02_table_loop.lua
-- TIME 4.945µs — string_03_nested.lua
return {
    "bug_01.lua",
    "bug_02.lua",
    "bug_03.lua",
    "bug_04.lua",
    "bug_06.lua",
    "bug_07a.lua",
    "bug_07b.lua",
    "bug_08.lua",
    "bug_09.lua",
    "bug_10b.lua",
    "bug_11.lua",
    "bug_12.lua",
    "bug_13.lua",
    "optfast.lua",
    "bug_16a.lua",
    "bug_16b.lua",
    "bug_17.lua",
    "bug_18.lua",
    "gauntlet_pA.lua",
    "gauntlet_pB.lua",
    "gauntlet_pC.lua",
    "gauntlet_pD.lua",
    "gauntlet_pE.lua",
    "gauntlet_pF.lua",
    "gauntlet_pG.lua",
    "gauntlet_pH.lua",
    "gauntlet_pI.lua",
    "gauntlet_pJ.lua",
    "gauntlet_pK.lua",
    "gauntlet_pL.lua",
    "gauntlet_pM.lua",
    "opt_literal_bound.lua",
    "region_table_resize.lua",
    "hoist_ctx_showcase.lua",
    "tier2_reg_limit.lua",
    "firewall_abort_all.lua",
    "firewall_global_offset.lua",
    "firewall_neg_offset.lua",
    "gauntlet_main.lua",
    "gauntlet_float.lua",
    "nested_01_success.lua",
    "nested_05_dyn_loop.lua",
    "nested_06_read_before_write.lua",
    "nested_07_read_then_table_store.lua",
    "nested_08_fresh_store.lua",
    "nested_10_alias_shared.lua",
    "nested_15_read_then_fresh.lua",
    "float_01_store_read.lua",
    "float_02_loop_gate.lua",
    "float_06_lazy_read.lua",
    "float_09_fast_rw.lua",
    "float_10_handle_mode.lua",
    "float_14_add_store.lua",
    "float_15_barista_space_cafe.lua",
    "tier4_01_flat_plus_nested.lua",
    "tier4_02_nested_read.lua",
    "tier4_03_rebind_decline.lua",
    "tier4_04_zero_iter.lua",
    "tier4_06_float_child.lua",
    "tier4_07_reg_limit_decline.lua",
    "tier4_08_zero_trip_init.lua",
    "tier4_09_multihop.lua",
    "tier4_10_matrix.lua",
    "tier4_11_matrix_float.lua",
    "tier4_12_unprovable_limit.lua",
    "tier4_13_matrix_fast_row.lua",
    "tier4_14_matrix_alias_decline.lua",
    "tier4_15_matrix_copy_reach.lua",
    "feat_if_01_phi_merge.lua",
    "feat_ops_01_arith.lua",
    "feat_ops_02_compare_bool.lua",
    "feat_ops_03_fast_leq.lua",
    "feat_ops_04_floor_neg.lua",
    "feat_ops_05_cmp_corners.lua",
    "feat_ops_06_bool_eq_variants.lua",
    "feat_ops_07_neg_zero.lua",
    "feat_ops_08_loop_forms.lua",
    "feat_ops_09_paren_gate.lua",
    "feat_ops_10_float_specials.lua",
    "feat_ops_11_precedence.lua",
    "feat_ops_12_if_store_gate.lua",
    "feat_if_02_phi_variants.lua",
    "feat_if_03_scope_shadow.lua",
    "probe_01_scalar.lua",
    "probe_02_loop_phi.lua",
    "probe_03_ec_offset.lua",
    "probe_04_leq_desugar_ec.lua",
    "probe_05_hoist_stability.lua",
    "probe_06_ssa_names.lua",
    "probe_07_mint_child.lua",
    "string_01_scalar.lua",
    "string_02_table_loop.lua",
    "string_03_nested.lua",
}
