-- generated by tests/milestone_lockdown.lua — do not edit by hand
-- locked: 2026-09-09 22:01:54
-- rustc 1.98.1 (48a229cea 2026-09-01) (Arch Linux rust 1:1.98.1-1.1)
-- TIME 3.025µs — bug_01.lua
-- TIME 2.646µs — bug_02.lua
-- TIME 2.749µs — bug_03.lua
-- TIME 9.73µs — bug_04.lua
-- TIME 1.947µs — bug_06.lua
-- TIME 4.588µs — bug_07a.lua
-- TIME 5.317µs — bug_07b.lua
-- TIME 2.883µs — bug_08.lua
-- TIME 130.608µs — bug_09.lua
-- TIME 3.055µs — bug_10b.lua
-- TIME 1.029µs — bug_11.lua
-- TIME 2.544µs — bug_12.lua
-- TIME 2.036µs — bug_13.lua
-- TIME 208.089µs — optfast.lua
-- TIME 1.205µs — bug_16a.lua
-- TIME 2.801µs — bug_16b.lua
-- TIME 2.962µs — bug_17.lua
-- TIME 971ns — bug_18.lua
-- TIME 2.244µs — gauntlet_pA.lua
-- TIME 10.429µs — gauntlet_pB.lua
-- TIME 1.161µs — gauntlet_pC.lua
-- TIME 1.968µs — gauntlet_pD.lua
-- TIME 280ns — gauntlet_pE.lua
-- TIME 6.359µs — gauntlet_pF.lua
-- TIME 2.819µs — gauntlet_pG.lua
-- TIME 2.51µs — gauntlet_pH.lua
-- TIME 1.101µs — gauntlet_pI.lua
-- TIME 2.572µs — gauntlet_pJ.lua
-- TIME 35.238µs — gauntlet_pK.lua
-- TIME 266ns — gauntlet_pL.lua
-- TIME 1.087µs — gauntlet_pM.lua
-- TIME 1.076µs — opt_literal_bound.lua
-- TIME 2.956µs — region_table_resize.lua
-- TIME 5.802µs — hoist_ctx_showcase.lua
-- TIME 249ns — tier2_reg_limit.lua
-- TIME 1.041µs — firewall_abort_all.lua
-- TIME 2.085µs — firewall_global_offset.lua
-- TIME 897ns — firewall_neg_offset.lua
-- TIME 1.9602732s — gauntlet_main.lua
-- TIME 332.394µs — gauntlet_float.lua
-- TIME 1.008µs — nested_01_success.lua
-- TIME 635ns — nested_05_dyn_loop.lua
-- TIME 285ns — nested_06_read_before_write.lua
-- TIME 1.74µs — nested_07_read_then_table_store.lua
-- TIME 1.803µs — nested_08_fresh_store.lua
-- TIME 1.554µs — nested_10_alias_shared.lua
-- TIME 1.737µs — nested_15_read_then_fresh.lua
-- TIME 1.442µs — float_01_store_read.lua
-- TIME 1.05µs — float_02_loop_gate.lua
-- TIME 1.232µs — float_06_lazy_read.lua
-- TIME 402ns — float_09_fast_rw.lua
-- TIME 1.011µs — float_10_handle_mode.lua
-- TIME 314ns — float_14_add_store.lua
-- TIME 1.983µs — tier4_01_flat_plus_nested.lua
-- TIME 2.171µs — tier4_02_nested_read.lua
-- TIME 1.209µs — tier4_03_rebind_decline.lua
-- TIME 904ns — tier4_04_zero_iter.lua
-- TIME 1.829µs — tier4_06_float_child.lua
-- TIME 2.181µs — tier4_07_reg_limit_decline.lua
-- TIME 415ns — tier4_08_zero_trip_init.lua
-- TIME 1.372µs — tier4_09_multihop.lua
-- TIME 1.792µs — tier4_10_matrix.lua
-- TIME 2.034µs — tier4_11_matrix_float.lua
-- TIME 1.628µs — tier4_12_unprovable_limit.lua
-- TIME 2.404µs — tier4_13_matrix_fast_row.lua
-- TIME 2.175µs — tier4_14_matrix_alias_decline.lua
-- TIME 1.397µs — tier4_15_matrix_copy_reach.lua
-- TIME 1.421µs — feat_if_01_phi_merge.lua
-- TIME 3.59µs — feat_ops_01_arith.lua
-- TIME 1.031µs — feat_ops_02_compare_bool.lua
-- TIME 937ns — feat_ops_03_fast_leq.lua
-- TIME 1.642µs — feat_ops_04_floor_neg.lua
-- TIME 173ns — feat_ops_05_cmp_corners.lua
-- TIME 275ns — feat_ops_06_bool_eq_variants.lua
-- TIME 1.952µs — feat_ops_07_neg_zero.lua
-- TIME 291ns — feat_ops_08_loop_forms.lua
-- TIME 1.05µs — feat_ops_09_paren_gate.lua
-- TIME 1.017µs — feat_ops_10_float_specials.lua
-- TIME 211ns — feat_ops_11_precedence.lua
-- TIME 230ns — feat_ops_12_if_store_gate.lua
-- TIME 277ns — feat_if_02_phi_variants.lua
-- TIME 1.181µs — feat_if_03_scope_shadow.lua
-- TIME 4.854µs — probe_01_scalar.lua
-- TIME 9.018µs — probe_02_loop_phi.lua
-- TIME 5.154µs — probe_03_ec_offset.lua
-- TIME 8.899µs — probe_04_leq_desugar_ec.lua
-- TIME 5.806µs — probe_05_hoist_stability.lua
-- TIME 3.975µs — probe_06_ssa_names.lua
-- TIME 5.826µs — probe_07_mint_child.lua
-- TIME 6.462µs — string_01_scalar.lua
-- TIME 10.638µs — string_02_table_loop.lua
-- TIME 5.749µs — string_03_nested.lua
return {
    "bug_01.lua",
    "bug_02.lua",
    "bug_03.lua",
    "bug_04.lua",
    "bug_06.lua",
    "bug_07a.lua",
    "bug_07b.lua",
    "bug_08.lua",
    "bug_09.lua",
    "bug_10b.lua",
    "bug_11.lua",
    "bug_12.lua",
    "bug_13.lua",
    "optfast.lua",
    "bug_16a.lua",
    "bug_16b.lua",
    "bug_17.lua",
    "bug_18.lua",
    "gauntlet_pA.lua",
    "gauntlet_pB.lua",
    "gauntlet_pC.lua",
    "gauntlet_pD.lua",
    "gauntlet_pE.lua",
    "gauntlet_pF.lua",
    "gauntlet_pG.lua",
    "gauntlet_pH.lua",
    "gauntlet_pI.lua",
    "gauntlet_pJ.lua",
    "gauntlet_pK.lua",
    "gauntlet_pL.lua",
    "gauntlet_pM.lua",
    "opt_literal_bound.lua",
    "region_table_resize.lua",
    "hoist_ctx_showcase.lua",
    "tier2_reg_limit.lua",
    "firewall_abort_all.lua",
    "firewall_global_offset.lua",
    "firewall_neg_offset.lua",
    "gauntlet_main.lua",
    "gauntlet_float.lua",
    "nested_01_success.lua",
    "nested_05_dyn_loop.lua",
    "nested_06_read_before_write.lua",
    "nested_07_read_then_table_store.lua",
    "nested_08_fresh_store.lua",
    "nested_10_alias_shared.lua",
    "nested_15_read_then_fresh.lua",
    "float_01_store_read.lua",
    "float_02_loop_gate.lua",
    "float_06_lazy_read.lua",
    "float_09_fast_rw.lua",
    "float_10_handle_mode.lua",
    "float_14_add_store.lua",
    "tier4_01_flat_plus_nested.lua",
    "tier4_02_nested_read.lua",
    "tier4_03_rebind_decline.lua",
    "tier4_04_zero_iter.lua",
    "tier4_06_float_child.lua",
    "tier4_07_reg_limit_decline.lua",
    "tier4_08_zero_trip_init.lua",
    "tier4_09_multihop.lua",
    "tier4_10_matrix.lua",
    "tier4_11_matrix_float.lua",
    "tier4_12_unprovable_limit.lua",
    "tier4_13_matrix_fast_row.lua",
    "tier4_14_matrix_alias_decline.lua",
    "tier4_15_matrix_copy_reach.lua",
    "feat_if_01_phi_merge.lua",
    "feat_ops_01_arith.lua",
    "feat_ops_02_compare_bool.lua",
    "feat_ops_03_fast_leq.lua",
    "feat_ops_04_floor_neg.lua",
    "feat_ops_05_cmp_corners.lua",
    "feat_ops_06_bool_eq_variants.lua",
    "feat_ops_07_neg_zero.lua",
    "feat_ops_08_loop_forms.lua",
    "feat_ops_09_paren_gate.lua",
    "feat_ops_10_float_specials.lua",
    "feat_ops_11_precedence.lua",
    "feat_ops_12_if_store_gate.lua",
    "feat_if_02_phi_variants.lua",
    "feat_if_03_scope_shadow.lua",
    "probe_01_scalar.lua",
    "probe_02_loop_phi.lua",
    "probe_03_ec_offset.lua",
    "probe_04_leq_desugar_ec.lua",
    "probe_05_hoist_stability.lua",
    "probe_06_ssa_names.lua",
    "probe_07_mint_child.lua",
    "string_01_scalar.lua",
    "string_02_table_loop.lua",
    "string_03_nested.lua",
}
